information atelier Deep Learning
AFPy/pyconfr_2016 pull request #61
Opened 2016-10-01 22:26 UTC by JGuillaumin

J'ai rajouté un lien vers la page où je vais annoncer les informations concernant l'atelier "Deep Learning"

2016-10-02 00:48 UTC, almet requested changes

2016-10-02 00:48 UTC, almet commented on content/pages/programme.rst
> +          Vous trouverez toutes les informations sur l'atelier (noatamment les librairies à installer) <a href="http://jguillaumin.github.io/2016-09-29-pycon-deep-learning/">ici</a>.</div>
Typo sur notamment

2016-10-04 14:34 UTC, Natim commented
@JGuillaumin peux-tu corriger la typo que je puisse publier ta modif ? Merci

2016-10-04 14:35 UTC, merged

2016-10-04 14:37 UTC, Natim commented
Nevermind 🗡